backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

# Media and public folders
media_folder: "public/images"
public_folder: "/images"

# Site configuration
site_url: https://your-blog-site.netlify.app
display_url: https://your-blog-site.netlify.app
logo_url: https://your-blog-site.netlify.app/favicon.svg

# Editorial workflow for content review
publish_mode: editorial_workflow

# Slug configuration
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - {
          label: "Title", 
          name: "title", 
          widget: "string",
          hint: "The main title of your blog post"
        }
      - {
          label: "Description", 
          name: "description", 
          widget: "text",
          hint: "A brief description that appears in previews and search results"
        }
      - {
          label: "Publish Date", 
          name: "pubDate", 
          widget: "datetime",
          default: "{{now}}",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DDTHH:mm:ss.sssZ"
        }
      - {
          label: "Updated Date", 
          name: "updatedDate", 
          widget: "datetime", 
          required: false,
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DDTHH:mm:ss.sssZ",
          hint: "Leave empty for new posts, update when making significant changes"
        }
      - {
          label: "Featured Image", 
          name: "heroImage", 
          widget: "image", 
          required: false,
          hint: "Optional hero image for the blog post (recommended size: 1200x600px)"
        }
      - {
          label: "Tags", 
          name: "tags", 
          widget: "list", 
          required: false,
          hint: "Add relevant tags to help categorize your post",
          field: {label: "Tag", name: "tag", widget: "string"}
        }
      - {
          label: "Draft", 
          name: "draft", 
          widget: "boolean", 
          default: false,
          hint: "Set to true to save as draft (won't appear on live site)"
        }
      - {
          label: "Body", 
          name: "body", 
          widget: "markdown",
          hint: "The main content of your blog post in Markdown format"
        }

  # Settings collection for site configuration
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site Configuration"
        name: "site"
        file: "src/config/site.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Site URL", name: "url", widget: "string"}
          - {label: "Author Name", name: "author", widget: "string"}
          - {label: "Author Email", name: "email", widget: "string"}
          - {label: "Social Media Links", name: "social", widget: "object", fields: [
              {label: "Twitter", name: "twitter", widget: "string", required: false},
              {label: "GitHub", name: "github", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
              {label: "Instagram", name: "instagram", widget: "string", required: false}
            ]}

# Editor configuration
editor:
  preview: true